---
title: "progress-report-ryannagao"
author: "Ryan Nagao"
date: "2024-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading Packages/Initializing Data

```{r, include = FALSE}
library(Lahman)
library(rvest)
library(tidyverse)
hof <- Lahman::HallOfFame
```

Preparing

```{r }
url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
tables <- html_table(html)

write.csv(tables[[1]], "temp.csv", row.names=FALSE)
backin <- readr::read_csv("temp.csv", skip = 1, show_col_types =FALSE)
head(backin, 3)
```

Tidying

```{r }
player_id <- function(playername){
  first <- tolower(str_split_i(playername, " ", 1))
  last <- tolower(str_split_i(playername, " ", 2))
  return(paste(substring(last,1,5), substring(first,1,2), "01", sep = ""))
}

backin$Name <- gsub("X-", "", backin$Name)
backin$Name <- gsub(" HOF", "", backin$Name)
backin$`playerID` <- player_id(backin$Name)

backin <- backin |>
  mutate(`yearID`      = 2023,
         `votedBy`     = "BBWAA",
         `ballots`     = 389,
         `needed`      = round(.75 * ballots),
         `votes`       = Votes,
         `inducted`    = factor(votes >= needed, labels = c("N","Y")),
         `category`    = "Player",
         `needed_note` = NaN) |>
  select(playerID,
         yearID,
         votedBy,
         ballots,
         needed,
         votes,
         inducted,
         category,
         needed_note)
```

Combining

```{r }
hof2023 <- rbind(hof,backin)
tail(hof2023, 28)
```

Read to CSV

```{r }
# readr::write_csv(hof2023, file = "HallOfFame.csv")
```

